bind 0.0.0.0
protected-mode yes

maxmemory 4gb
maxmemory-policy noeviction

appendonly yes
appendfsync everysec
no-appendfsync-on-rewrite no

save 900 1
save 300 10
save 60 10000

loglevel notice
logfile ""
